dist: xenial
sudo: false
language: python
cache: pip

env:
  global:
  - PYTHONPATH="./tests/"
  - DJANGO_SETTINGS_MODULE="settings_test"

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

install: pip install tox-travis
script: tox

deploy:
  provider: pypi
  user: azavea
  password:
    secure: aUHpgXoIvOP3lhLhx8E+EKRP0tbTuzLXg/hp68jtslMHywsud1/8V3x7E37wOEq1BcYBMyS5oqGqXGCO2NIYgEt8kENCilvTLau6LI9nIcV7Us57VpDNBdFw48KmV03a7lzIpayj+Sg36aWXgwxYr0lj/4XF6mn50RaeiB7L91cPtlIAS1VU58RTq3utuZ1fPiYc97C4TwYYe7T5xkZSzxUR6XWAZ4X6/xKE36Ee1l7hTQoGUsjKD5zUkqjDE0piR5yjQMhQQYTC8rkM0pnRSBaIplbra4048O81eHnt6GDdZFJSlrRIS9/sduPJ3p5B0h0SPX9VOEEtF0EaeIm6bvjrPkHuo20SfzbTRp6UXlrGlbXykP0KzJKCEh9iDvgcpv/B6i+buOtGC45PD6qu2a0wt34VvWwVnjvQju6Ui7sGYtpEDnhbJp4wLMJGvl/xfHJURuoSQ68G1JVya1toLfy3iXoL1EZBBREh+rJOJrHJaMGBSdnysCH2dt2fb/px/+8OWhcfqCn7oupysI+xb5rQo/8pbxckzAmn5Q/we5yGccX+x1Gw8bITQB01nHO9aRO/PIXipjJILP5cWj3/KUEaGpTBVfVPW4YESqgSeKYwBdxD+xgh/HalMU/0281z/AJVg0DjQT0uFhA1mDFEFE2R0h8r7ASX9YlMd3M9H+U=
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "3.7"
    repo: azavea/django-ecsmanage
